package com.example.fulluikotlin.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color


data class FullColors(
    val background: Color,
    val bgImageColor: Color,
    val textWelcomeLogin: Color,
    val textDiscriptLogin: Color,
    val bgFieldLogin: Color,
    val textLabelFieldLogin: Color,
    val bgBottomBar: Color,
    val itemBottomBarUnslected: Color,
    val shadowBackground: Color,
    val bgToolbarButton: Color,
    val purple: Color,
    val purple2: Color,
    val whitBlack: Color,
    val iconColor: Color,
    val bgServerSelected: Color,
    val textValueAmount: Color,
    val textAmount: Color,
    val pingText: Color,
    val timeText: Color,
    val statusTextIcon: Color,
    val bgStatusDisconnect: Color,
    val bgStatusConnecting: Color,
    val bgStatusConnected: Color,
    val textStatusDisconnect: Color,
    val textStatusConnecting: Color,
    val textStatusConnected: Color,
    val bgButtonL1Connecting: Color,
    val bgButtonL2Connecting: Color,
    val bgButtonL3Connecting: Color,
    val bgButtonL1Connected: Color,
    val bgButtonL2Connected: Color,
    val bgButtonL1DisConnect: Color,
    val bgButtonL2DisConnect: Color,
    val bgButtonL3DisConnect: Color,
    val iconOpenServer: Color,
    val bgServesList: Color,
    val borderServesList: Color,
    val bgFlagServesList: Color,
    val dividerServers: Color,
    val pingServers: Color,
    val unCheckRadioServer: Color,
    val textSplitTunnel: Color,
    val borderSearchBar: Color,
    val borderItemsSplit: Color,
    val checkBoxItemsSplit: Color,
    val uncheckBoxItemsSplit: Color,
    val textItemSplit: Color,
    val dragHandleBottomSheet: Color,
    val textDiscriptionHintSplit: Color,
    val bgBottomSheet: Color,
    val bgProfile: Color,
    val textAccountTypyProfile: Color,
    val borderCardAccountProfile: Color,
    val bgCardAccountProfile: Color,
    val textItemsProfile: Color,
    val thumbCheckProfile: Color,
    val thumbUnCheckProfile: Color,
    val trackUnCheckProfile: Color,
    val textActiveService: Color,
    val iconTitleActiveService: Color,
    val arrowProfile: Color,
    val iconActiveService: Color,
    val dividerActiveService: Color,
    val buttonActiveService: Color,
    val textTitleDevicesActive: Color,
    val textLastActiveDevicesActive: Color,
    val bgDiscExitDevice: Color,
    val buttonBackExitDialog: Color,
    val txtDiscAboutUs: Color,
    val iconSocailMediaAboutUs: Color,
    val buttonAcceptDialog: Color,
    val textDismissDialog: Color,
    val buttonDismissDialog: Color,
    val textAcceptDialog: Color,
    val whit: Color,
    val green: Color,
    val red: Color,
    val red2: Color,
    val red3: Color,
    val grayDark: Color,
    val grayDark2: Color,
    val GrayDark7: Color,
    val primary: Color,
    val secondary: Color,
    val transparent: Color,
)

private val DarkFullColors = FullColors(
    background = BlueDarkBg,
    bgImageColor = Whit5Percent,
    textWelcomeLogin = Whit,
    textDiscriptLogin = Black4,
    bgFieldLogin = Whit6Percent,
    textLabelFieldLogin = GrayDark6,
    bgBottomBar = Whit10Percent,
    itemBottomBarUnslected = GrayDark7,
    shadowBackground = BlueShadowDark.copy(alpha = 0.7f),
    bgToolbarButton = Whit6Percent,
    purple = Purple,
    purple2 = Purple2,
    whitBlack = Whit,
    iconColor = Whit,
    bgServerSelected = Whit10Percent,
    textValueAmount = Whit,
    textAmount = Whit,
    pingText = Gray,
    timeText = Whit,
    statusTextIcon = Whit,
    bgStatusDisconnect = GrayDark,
    bgStatusConnecting = Orange3,
    bgStatusConnected = Purple45Percent,
    textStatusDisconnect = Whit,
    textStatusConnecting = Whit,
    textStatusConnected = Whit,
    bgButtonL1Connecting = Orange6Percent,
    bgButtonL2Connecting = Orange26Percent,
    bgButtonL3Connecting = Orange,
    bgButtonL1Connected = Purple30Percent,
    bgButtonL2Connected = Purple,
    bgButtonL1DisConnect = GrayDark,
    bgButtonL2DisConnect = BlueDark,
    bgButtonL3DisConnect = GrayDark,
    iconOpenServer = GrayDark6,
    bgServesList = Whit5Percent,
    borderServesList = Color.Transparent,
    bgFlagServesList = Whit10Percent,
    dividerServers = Whit8Percent,
    pingServers = GrayDark5,
    unCheckRadioServer = Whit,
    textSplitTunnel = Whit,
    borderSearchBar = GrayDark6,
    borderItemsSplit = Color.Transparent,
    checkBoxItemsSplit = Whit,
    uncheckBoxItemsSplit = GrayDark7,
    textItemSplit = Whit,
    dragHandleBottomSheet = GrayDark7,
    textDiscriptionHintSplit = GrayDark7,
    bgBottomSheet = BlueDark2,
    bgProfile = Whit20Percent,
    textAccountTypyProfile = Whit,
    borderCardAccountProfile = Color.Transparent,
    bgCardAccountProfile = Whit5Percent,
    textItemsProfile = Whit,
    thumbCheckProfile = Whit7,
    thumbUnCheckProfile = GrayDark7,
    trackUnCheckProfile = GrayDark8,
    textActiveService = Whit,
    iconTitleActiveService = Whit,
    arrowProfile = Whit,
    iconActiveService = Whit,
    dividerActiveService = BlueDark2,
    buttonActiveService = Whit,
    textTitleDevicesActive = Whit,
    textLastActiveDevicesActive = Whit63Percent,
    bgDiscExitDevice = Whit12Percent,
    buttonBackExitDialog = Whit,
    txtDiscAboutUs = Whit,
    iconSocailMediaAboutUs = Whit,
    buttonDismissDialog = Whit,
    textDismissDialog = Whit,
    buttonAcceptDialog = Purple,
    textAcceptDialog = Whit,
    whit = Whit,
    green = Green.copy(alpha = 0.48f),
    red = Red.copy(alpha = 0.48f),
    red2 = Red2,
    red3 = Red3,
    grayDark = GrayDark,
    grayDark2 = GrayDark2,
    GrayDark7 = GrayDark7,
    primary = Color(0xFF64B5F6),
    secondary = Color(0xFF1E88E5),
    transparent = Transparent
)

private val LightFullColors = FullColors(
    background = WhitBg,
    bgImageColor = GrayDark12,
    textWelcomeLogin = Black3,
    textDiscriptLogin = Black5,
    bgFieldLogin = Whit3,
    textLabelFieldLogin = GrayDark2,
    bgBottomBar = Whit,
    itemBottomBarUnslected = GrayDark2,
    shadowBackground = Transparent,
    bgToolbarButton = Whit,
    purple = Purple,
    purple2 = Purple2,
    whitBlack = Black,
    iconColor = GrayDark2,
    bgServerSelected = GrayLight,
    textValueAmount = GrayDark1,
    textAmount = GrayDark2,
    pingText = Black60percent,
    timeText = GrayDark3,
    statusTextIcon = GrayDark4,
    bgStatusDisconnect = GrayDark15,
    bgStatusConnecting = Orange2,
    bgStatusConnected = Purple9Percent,
    textStatusDisconnect = GrayDark4,
    textStatusConnecting = Orange4,
    textStatusConnected = Purple,
    bgButtonL1Connecting = Orange11Percent,
    bgButtonL2Connecting = Orange26Percent,
    bgButtonL3Connecting = Orange,
    bgButtonL1Connected = Purple30Percent,
    bgButtonL2Connected = Purple,
    bgButtonL1DisConnect = GrayDark13,
    bgButtonL2DisConnect = GrayDark14,
    bgButtonL3DisConnect = Whit25Percent,
    iconOpenServer = GrayDark7,
    bgServesList = Whit,
    borderServesList = GrayDark7,
    bgFlagServesList = Purple10Percent,
    dividerServers = Black8percent,
    pingServers = GrayDark5,
    unCheckRadioServer = GrayDark6,
    textSplitTunnel = Black2,
    borderSearchBar = GrayDark5,
    borderItemsSplit = GrayDark7,
    checkBoxItemsSplit = Purple,
    uncheckBoxItemsSplit = GrayDark7,
    textItemSplit = Black2,
    dragHandleBottomSheet = GrayDark7,
    textDiscriptionHintSplit = Black2,
    bgBottomSheet = Whit,
    bgProfile = Purple,
    textAccountTypyProfile = GrayDark5,
    borderCardAccountProfile = GrayDark7,
    bgCardAccountProfile = Whit,
    textItemsProfile = Black2,
    thumbUnCheckProfile = Whit5,
    thumbCheckProfile = Whit7,
    trackUnCheckProfile = Whit6,
    textActiveService = Black2,
    iconTitleActiveService = Black6,
    arrowProfile = GrayDark7,
    iconActiveService = GrayDark5,
    dividerActiveService = GrayDark9,
    buttonActiveService = Purple,
    textTitleDevicesActive = Black2,
    textLastActiveDevicesActive = GrayDark2,
    bgDiscExitDevice = Black4percent,
    buttonBackExitDialog = GrayDark2,
    txtDiscAboutUs = GrayDark10,
    iconSocailMediaAboutUs = GrayDark11,
    buttonDismissDialog = Purple,
    textDismissDialog = Purple,
    buttonAcceptDialog = Purple,
    textAcceptDialog = Whit,
    whit = Whit,
    green = Green,
    red = Red,
    red2 = Red2,
    red3 = Red3,
    grayDark = GrayDark,
    grayDark2 = GrayDark2,
    GrayDark7 = GrayDark7,
    primary = Color(0xFF1976D2),
    secondary = Color(0xFF90CAF9),
    transparent = Transparent
)


@Composable
fun FullKotlinTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
) {
    val fullColors = if (darkTheme) DarkFullColors else LightFullColors

    CompositionLocalProvider(
        LocalFullColors provides fullColors,
        LocalDarkTheme provides darkTheme

    ) {
        MaterialTheme(
            typography = Typography,
            content = content
        )
    }
}

val LocalFullColors = staticCompositionLocalOf<FullColors> {
    error("FullColors not provided")
}

val MaterialTheme.fullColors: FullColors
    @Composable
    get() = LocalFullColors.current

val LocalDarkTheme = staticCompositionLocalOf<Boolean> { false }
